# Generated by Django 6.1.1 on 2026-09-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('username', models.CharField(max_length=255)),
                ('hostname', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField()),
                ('interface', models.CharField(max_length=255)),
                ('view', models.BooleanField(default=False)),
            ],
        ),
    ]
